import "@/styles/reset.css";
import { Header } from "@/components/header"

export const metadata = {
  title: "ADMIN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}