import "@/styles/reset.css";
import { Header } from "@/components/header"

export const metadata = {
  title: "Recipea",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const selam = await fetch("http://localhost:5170/api/test/recipeoftheday").then(res=>res.json())

  // console.log(selam.title)
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}